setup.template.settings:
  ####指定索引的分区数
  index.number_of_shards: 1
  index.codec: best_compression
output.elasticsearch:  #指定ES的配置
  hosts: ["192.168.0.127:9200","192.168.0.128:9200","192.168.0.129:9200"]
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enable: false
setup.kibana:
  host: "192.168.0.130:5601"
